version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
      - VITE_API_BASE_URL=http://your-backend-server:8000
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    image: your-backend-image:latest
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=your-database-url
      - JWT_SECRET=your-jwt-secret
    restart: unless-stopped

networks:
  default:
    name: wb_network